# Generated by Django 5.1.7 on 2025-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-date"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={
                "ordering": ["name"],
                "verbose_name": "Коттедж",
                "verbose_name_plural": "Коттеджи",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.booking",
                verbose_name="Связанное бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на мероприятие"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="event_images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(verbose_name="Место проведения"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.TextField(
                blank=True,
                help_text="Перечислите удобства, каждое с новой строки",
                verbose_name="Удобства",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="capacity",
            field=models.IntegerField(verbose_name="Вместимость (чел.)"),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Подробное описание коттеджа для посетителей",
                verbose_name="Описание коттеджа",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.employee",
                verbose_name="Ответственный сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="house_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID дома"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="image",
            field=models.ImageField(
                help_text="Файл должен находиться в папке static/images/",
                upload_to="",
                verbose_name="Название файла изображения",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Местоположение"),
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название коттеджа"),
        ),
        migrations.AlterField(
            model_name="house",
            name="price_per_night",
            field=models.IntegerField(verbose_name="Цена за ночь (руб.)"),
        ),
        migrations.AlterField(
            model_name="house",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="URL-идентификатор",
            ),
        ),
    ]
