# Generated by Django 5.1.7 on 2025-05-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0002_alter_event_options_alter_house_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="employee_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recreation.employee",
                verbose_name="Сотрудник",
            ),
        ),
    ]
