# Generated by Django 5.1.7 on 2025-05-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0004_alter_review_options_review_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="id",
            new_name="event_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="booking_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.booking",
                verbose_name="Бронирование",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="employee_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.employee",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.booking",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(upload_to="event_images/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="house",
            name="image",
            field=models.ImageField(
                help_text="Загрузите изображение коттеджа",
                upload_to="houses/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(verbose_name="Дата платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=50, verbose_name="Способ оплаты"),
        ),
    ]
