# Generated by Django 5.1.7 on 2025-05-12 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0005_alter_event_options_alter_review_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID бронирования"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateField(verbose_name="Дата заезда"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(verbose_name="Дата выезда"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="house_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.house",
                verbose_name="Коттедж",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Общая стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="booking_date",
            field=models.DateField(verbose_name="Дата бронирования"),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="booking_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.booking",
                verbose_name="Бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="return_date",
            field=models.DateField(verbose_name="Дата возврата"),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="additional_file",
            field=models.FileField(
                upload_to="client_files/", verbose_name="Дополнительный файл"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="client",
            name="patronymic",
            field=models.CharField(max_length=100, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_info",
            field=models.CharField(
                max_length=255, verbose_name="Контактная информация"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID сотрудника"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="patronymic",
            field=models.CharField(max_length=100, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="booking_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.booking",
                verbose_name="Бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на мероприятие"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                upload_to="event_images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(verbose_name="Место проведения"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID оборудования"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="house_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.house",
                verbose_name="Коттедж",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Расположение"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.TextField(blank=True, verbose_name="Удобства"),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="house",
            name="image",
            field=models.ImageField(upload_to="houses/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название должности"),
        ),
        migrations.AlterField(
            model_name="position",
            name="position_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID должности"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="responsibilities",
            field=models.TextField(verbose_name="Обязанности"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                upload_to="post_images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, verbose_name="URL-адрес"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                default="draft",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts",
                through="recreation.PostTag",
                to="recreation.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="review",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="house_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.house",
                verbose_name="Коттедж",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                upload_to="service_images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название услуги"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID услуги"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название тега"),
        ),
    ]
