# Generated by Django 5.1.7 on 2025-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0006_alter_facility_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="houses/", verbose_name="Изображение"
            ),
        ),
    ]
