# Generated by Django 5.1.7 on 2025-05-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0015_remove_booking_employee_id_booking_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="house_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="base_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Базовая стоимость",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="client_name",
            field=models.CharField(
                default="Не указано", max_length=255, verbose_name="Имя клиента"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                default="email@email.com", max_length=254, verbose_name="Email"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(
                default=2, verbose_name="Количество гостей"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="house",
            field=models.ForeignKey(
                blank=True,
                db_column="house_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recreation.house",
                verbose_name="Коттедж",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(
                default="+7XXXXXXXXXX", max_length=20, verbose_name="Телефон"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                to="recreation.service",
                verbose_name="Дополнительные услуги",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recreation.client",
                verbose_name="Клиент",
            ),
        ),
    ]
