# Generated by Django 5.1.7 on 2025-05-26 18:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0017_client_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'Тег поста', 'verbose_name_plural': 'Теги постов'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('entertainment', 'Развлечения'), ('food', 'Питание'), ('transport', 'Транспорт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.FileField(blank=True, help_text='Загрузите сканы документов (паспорт, водительские права и т.д.)', null=True, upload_to='client_documents/%Y/%m/%d/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=ckeditor.fields.RichTextField(verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='position',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, unique_for_date='publish', verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение'),
        ),
    ]
