# Generated by Django 5.1.7 on 2025-06-14 11:05

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0019_alter_service_type_dzexam"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBooking",
            fields=[
                (
                    "booking_id",
                    models.IntegerField(
                        blank=True, db_index=True, verbose_name="ID бронирования"
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Дата заезда")),
                ("check_out_date", models.DateField(verbose_name="Дата выезда")),
                (
                    "guests",
                    models.PositiveIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "client_name",
                    models.CharField(
                        default="Не указано", max_length=255, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Базовая стоимость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(null=True, verbose_name="Дата создания"),
                ),
                (
                    "comment",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        db_column="house_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.house",
                        verbose_name="Коттедж",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Бронирование",
                "verbose_name_plural": "historical Бронирования",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHouse",
            fields=[
                (
                    "house_id",
                    models.IntegerField(
                        blank=True, db_index=True, verbose_name="ID дома"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название коттеджа"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, verbose_name="URL-идентификатор"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Местоположение"),
                ),
                ("capacity", models.IntegerField(verbose_name="Вместимость (чел.)")),
                (
                    "price_per_night",
                    models.IntegerField(verbose_name="Цена за ночь (руб.)"),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "amenities",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Удобства"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recreation.employee",
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Коттедж",
                "verbose_name_plural": "historical Коттеджи",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
