# Generated by Django 5.1.7 on 2025-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0020_historicalbooking_historicalhouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата приема"),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="historicalhouse",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Местоположение"),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Местоположение"),
        ),
    ]
