# Generated by Django 4.2.23 on 2025-06-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recreation",
            "0021_employee_email_employee_hire_date_employee_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalhouse",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical house",
                "verbose_name_plural": "historical houses",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={},
        ),
        migrations.RemoveField(
            model_name="historicalhouse",
            name="amenities",
        ),
        migrations.RemoveField(
            model_name="historicalhouse",
            name="description",
        ),
        migrations.RemoveField(
            model_name="house",
            name="amenities",
        ),
        migrations.RemoveField(
            model_name="house",
            name="description",
        ),
    ]
