# Generated by Django 4.2.23 on 2025-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recreation",
            "0022_alter_historicalhouse_options_alter_house_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DZexam",
        ),
    ]
