# Generated by Django 4.2.23 on 2025-06-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0023_delete_dzexam"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalhouse",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Коттедж",
                "verbose_name_plural": "historical Коттеджи",
            },
        ),
        migrations.AlterModelOptions(
            name="house",
            options={"verbose_name": "Коттедж", "verbose_name_plural": "Коттеджи"},
        ),
    ]
