# Generated by Django 4.2.23 on 2025-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recreation", "0024_alter_historicalhouse_options_alter_house_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhouse",
            name="amenities",
            field=models.TextField(blank=True, null=True, verbose_name="Удобства"),
        ),
        migrations.AddField(
            model_name="historicalhouse",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="house",
            name="amenities",
            field=models.TextField(blank=True, null=True, verbose_name="Удобства"),
        ),
        migrations.AddField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
